name: package

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        include:
          - python: 3.8
          - python: 3.13

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y libsndfile1

      - name: Install
        run: make PYTHON_VERSION=${{ matrix.python }}

      - name: Check
        run: make check

      - name: Test
        run: make test

      - name: Coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
